<a href="https://colab.research.google.com/github/kkvk001/iNeuron/blob/main/L-21-numpy-class-2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 

In [ ]:
range(10)

range(0, 10)

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list(range(3 ,10))

[3, 4, 5, 6, 7, 8, 9]

In [ ]:
list(range(3 ,10.5))

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(.5 , 10)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [ ]:
np.arange(5 ,-4, -1)

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3])

In [ ]:
np.arange(5 ,-4, -.5)

array([ 5. ,  4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ,
       -0.5, -1. , -1.5, -2. , -2.5, -3. , -3.5])

In [ ]:
list(np.linspace(1,5,20,retstep=True))

[array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
        2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
        3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
        4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]),
 0.21052631578947367]

In [ ]:
np.logspace(1,50,10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((3,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,4,2)) *5 

array([[[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]]])

In [ ]:
np.empty((2,3))

array([[4.65789755e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [ ]:
a = np.eye(4)

In [ ]:
a.shape

(4, 4)

In [ ]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
a.size

16

In [ ]:
a.ndim

2

In [ ]:
a1 = np.random.randn(3,4)

In [ ]:
a1

array([[ 0.89197116, -1.15365104, -0.05745584,  0.12046936],
       [ 0.09741326,  0.30017453,  0.75902832,  0.16031268],
       [ 0.35616933,  1.68695656,  1.2776625 , -0.22306634]])

In [ ]:
import pandas as pd 

In [ ]:
pd.DataFrame(a1)

0         1         2         3
0  0.891971 -1.153651 -0.057456  0.120469
1  0.097413  0.300175  0.759028  0.160313
2  0.356169  1.686957  1.277662 -0.223066

In [ ]:
a1

array([[ 0.89197116, -1.15365104, -0.05745584,  0.12046936],
       [ 0.09741326,  0.30017453,  0.75902832,  0.16031268],
       [ 0.35616933,  1.68695656,  1.2776625 , -0.22306634]])

In [ ]:
a1[1][1]

0.3001745329451818

In [ ]:
a1[0:2 , 0:2]

array([[ 0.89197116, -1.15365104],
       [ 0.09741326,  0.30017453]])

In [ ]:
a1[[0,1] , 0:2]

array([[ 0.89197116, -1.15365104],
       [ 0.09741326,  0.30017453]])

In [ ]:
a1[[0,1] ,0:2]

array([[ 0.89197116, -1.15365104],
       [ 0.09741326,  0.30017453]])

In [ ]:
a1

array([[ 0.89197116, -1.15365104, -0.05745584,  0.12046936],
       [ 0.09741326,  0.30017453,  0.75902832,  0.16031268],
       [ 0.35616933,  1.68695656,  1.2776625 , -0.22306634]])

In [ ]:
a1[[1,2],3]

array([ 0.16031268, -0.22306634])

In [ ]:
m1 = np.random.randint(1,3 , (3,3))

In [ ]:
m1

array([[2, 2, 1],
       [1, 2, 2],
       [1, 2, 1]])

In [ ]:
m2 = np.random.randint(2,4 , (3,3))

In [ ]:
m2

array([[3, 2, 2],
       [3, 2, 3],
       [2, 3, 2]])

In [ ]:
m1*m2

array([[6, 4, 2],
       [3, 4, 6],
       [2, 6, 2]])

In [ ]:
m1@m2

array([[14, 11, 12],
       [13, 12, 12],
       [11,  9, 10]])

In [ ]:
m1

array([[2, 2, 1],
       [1, 2, 2],
       [1, 2, 1]])

In [ ]:
m2

array([[3, 2, 2],
       [3, 2, 3],
       [2, 3, 2]])

In [ ]:
m1

array([[2, 2, 1],
       [1, 2, 2],
       [1, 2, 1]])

In [ ]:
pow(m1 , 4)

array([[16, 16,  1],
       [ 1, 16, 16],
       [ 1, 16,  1]])

In [ ]:
np.sqrt(m1)

array([[1.41421356, 1.41421356, 1.        ],
       [1.        , 1.41421356, 1.41421356],
       [1.        , 1.41421356, 1.        ]])

In [ ]:
np.log10(m1)

array([[0.30103, 0.30103, 0.     ],
       [0.     , 0.30103, 0.30103],
       [0.     , 0.30103, 0.     ]])

In [ ]:
np.exp(m1)

array([[7.3890561 , 7.3890561 , 2.71828183],
       [2.71828183, 7.3890561 , 7.3890561 ],
       [2.71828183, 7.3890561 , 2.71828183]])

In [ ]:
m1**2


array([[4, 4, 1],
       [1, 4, 4],
       [1, 4, 1]])